# - name: check system os and falvour information
#   hosts: local
#   connection: local
#   tasks:
#   - name: check system information 
#     ansible.builtin.yum: name=java-1.8.0-openjdk state=installed
#     when: 
#     - ansible_os_family == "RedHat" and  ansible_pkg_mgr == "apt"
#     - ansible_os_family == "RedHat" or  ansible_pkg_mgr == "yum"
#     - ansible_distribution_version >= "22.04"
    
    

---
- name: Check system OS and flavor information
  hosts: local
  connection: local

  tasks:
    - name: Install Java on RedHat-based systems
      ansible.builtin.yum:
        name: java-1.8.0-openjdk
        state: present
      when: 
        - ansible_os_family == "RedHat"
        - ansible_pkg_mgr == "yum"

    - name: Install Java on Debian-based systems
      ansible.builtin.apt:
        name: openjdk-8-jdk
        state: present
      when: 
        - ansible_os_family == "Debian"
        - ansible_pkg_mgr == "apt"
        - ansible_distribution_version >= "22.04"
        - ansible_distribution_version <= "20.04"
        - ansible_distribution_version == "21.04"
        - ansible_distribution_version != "23.04"
