- name: Ignore Errors
  hosts: localhost
  connection: local
  tasks:
    - name: create packages
      ansible.builtin.shell: sleep 60
      async: 20
      poll: 10
    - name: install package use shell
      shell: dnf install htop -y
