- name: async and polling , we can restrict the time for onlyy to execute playbbok inside tasks
  hosts: localhost
  connection: local
  tasks:
    - name: create packages
      ansible.builtin.shell: sleep 20
      async: 20
      poll: 10
    - name: install package use shell
      shell: dnf install htop -y
